server:
  port: 985

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: root
    password: 1234
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    cleanDisabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret

logging:
  level:
    org:
      springframework: INFO
      hibernate: DEBUG
    com:
      notes: INFO